services:
  postgres:
    image: postgres:16-alpine
    container_name: gameball-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gameball
      POSTGRES_PASSWORD: gameball_dev
      POSTGRES_DB: gameball_ecommerce
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
